package algorithm.recursive;

/**
 * https://www.geeksforgeeks.org/print-subsequences-string/
 * 
 * Given a string, we have to find out all subsequences of it. A String is a
 * subsequence of a given String, that is generated by deleting some character
 * of a given string without changing its order.
 * 
 * Input : abc
 * Output : a, b, c, ab, bc, ac, abc
 * 
 * Input : aaa
 * Output : a, aa, aaa
 * 
 */
public class PrintSubsequence {


    public static void main(String args[]) {
        String str1 = "abc";
        String str2 = "aaa";
        printSubseq(str1, 0, "");
    }

    public static void printSubseq(String str, int idx, String res) {
        if (idx == str.length()) {
            System.out.println(res);
            return;
        }
        //choose
        printSubseq(str, idx + 1, res + str.charAt(idx));
        //don't choose
        printSubseq(str, idx + 1, res);
    }

}
